project:
  type: website

website:
  title: "[R] for research"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tvheffer
      - icon: twitter
        href: https://twitter.com/heffer-taylor
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

comments:
  giscus:
    repo: tvheffer/t_heffer_blog